import streamlit as st
import sqlite3
import pandas as pd
from pathlib import Path


# ============================================================
# PATH CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

# Existing SQLite database - used mainly for audit/governance
DB_PATH = BASE_DIR / "data" / "ews_cm_database.db"

# Synthetic data generated by src/main.py
OUTPUT_DIR = BASE_DIR / "output"

BORROWER_FILE = OUTPUT_DIR / "borrower_master_200.csv"
EWS_FILE = OUTPUT_DIR / "ews_results_200.csv"
EWS_RAW_FILE = OUTPUT_DIR / "ews_raw_inputs_200.csv"
CM_FILE = OUTPUT_DIR / "credit_monitoring_results_200.csv"
CM_RAW_FILE = OUTPUT_DIR / "credit_monitoring_raw_inputs_200.csv"
ALERT_FILE = OUTPUT_DIR / "ews_alerts.csv"


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI EWS & Credit Monitoring",
    page_icon="🚨",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ============================================================
# HEADER
# ============================================================

st.title("🚨 AI Early Warning System & Credit Monitoring")

st.caption(
    "Corporate Borrower Risk Monitoring | "
    "EWS • Credit Monitoring • Explainability • "
    "Human Review • Audit"
)


# ============================================================
# DATA LOADING
# ============================================================

@st.cache_data(ttl=30)
def load_csv(file_path):

    if not file_path.exists():
        return pd.DataFrame()

    try:

        df = pd.read_csv(file_path)

        # Convert object columns to string for Streamlit/PyArrow stability
        for col in df.columns:

            if df[col].dtype == "object":
                df[col] = df[col].astype(str)

        return df

    except Exception as e:

        st.error(
            f"Error reading {file_path.name}: {e}"
        )

        return pd.DataFrame()


@st.cache_data(ttl=30)
def load_db_table(table_name):

    if not DB_PATH.exists():
        return pd.DataFrame()

    conn = sqlite3.connect(
        DB_PATH
    )

    try:

        df = pd.read_sql_query(
            f"SELECT * FROM {table_name}",
            conn
        )

        for col in df.columns:

            if df[col].dtype == "object":
                df[col] = df[col].astype(str)

    except Exception:

        df = pd.DataFrame()

    finally:

        conn.close()

    return df


# ============================================================
# SAVE HUMAN REVIEW / AUDIT ACTION
# ============================================================

def save_audit_action(
    account_num,
    decision,
    rationale,
    reviewer_id="CO_001"
):

    # Make sure data directory exists
    DB_PATH.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    conn = sqlite3.connect(
        DB_PATH
    )

    cursor = conn.cursor()

    # Create audit table if it does not exist
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_trail (

            id INTEGER PRIMARY KEY AUTOINCREMENT,

            account_number TEXT,

            decision TEXT,

            rationale TEXT,

            reviewer_id TEXT,

            timestamp TIMESTAMP
                DEFAULT CURRENT_TIMESTAMP

        )
        """
    )

    # Insert review action
    cursor.execute(
        """
        INSERT INTO audit_trail
        (
            account_number,
            decision,
            rationale,
            reviewer_id
        )
        VALUES (?, ?, ?, ?)
        """,
        (
            account_num,
            decision,
            rationale,
            reviewer_id
        )
    )

    conn.commit()
    conn.close()

    # Clear cached database results
    st.cache_data.clear()


# ============================================================
# LOAD SYNTHETIC DATA
# ============================================================

borrower_df = load_csv(
    BORROWER_FILE
)

ews_df = load_csv(
    EWS_FILE
)

ews_raw_df = load_csv(
    EWS_RAW_FILE
)

cm_df = load_csv(
    CM_FILE
)

cm_raw_df = load_csv(
    CM_RAW_FILE
)

alerts_df = load_csv(
    ALERT_FILE
)


# ============================================================
# CHECK EWS DATA
# ============================================================

if ews_df.empty:

    st.error(
        "No EWS result data is available."
    )

    st.info(
        "Generate the synthetic dataset first by running:"
    )

    st.code(
        "python -m src.main"
    )

    st.stop()


# ============================================================
# HELPER FUNCTION
# ============================================================

def find_column(
    df,
    possible_names
):

    if df.empty:
        return None

    for name in possible_names:

        if name in df.columns:
            return name

    return None


# ============================================================
# IDENTIFY IMPORTANT COLUMNS
# ============================================================

borrower_id_col = find_column(
    ews_df,
    [
        "Borrower_ID",
        "Account_Number",
        "Account_Number_ID",
        "BorrowerID"
    ]
)


score_col = find_column(
    ews_df,
    [
        "Overall_Normalized_Score",
        "Overall_Risk_Score",
        "Overall_Score"
    ]
)


risk_band_col = find_column(
    ews_df,
    [
        "Risk_Band",
        "RiskBand"
    ]
)


status_col = find_column(
    ews_df,
    [
        "Final_Status",
        "Status"
    ]
)


critical_col = find_column(
    ews_df,
    [
        "Critical_Indicator_Override",
        "Critical_Override"
    ]
)


# ============================================================
# MERGE BORROWER MASTER + EWS RESULTS
# ============================================================

dashboard_df = ews_df.copy()


if (
    not borrower_df.empty
    and borrower_id_col
):

    master_id_col = find_column(
        borrower_df,
        [
            "Borrower_ID",
            "Account_Number",
            "BorrowerID"
        ]
    )

    if master_id_col:

        # Rename master ID if necessary
        if master_id_col != borrower_id_col:

            borrower_df = borrower_df.rename(
                columns={
                    master_id_col:
                    borrower_id_col
                }
            )

        dashboard_df = borrower_df.merge(
            ews_df,
            on=borrower_id_col,
            how="left",
            suffixes=(
                "",
                "_EWS"
            )
        )


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title(
    "⚙️ Dashboard Controls"
)

st.sidebar.markdown(
    "### Data Source"
)

st.sidebar.success(
    "Synthetic 200-Borrower Dataset"
)

st.sidebar.caption(
    "Generated using Faker + NumPy "
    "and scored using the EWS engine."
)


# ============================================================
# IDENTIFY FILTER COLUMNS
# ============================================================

sector_col = find_column(
    dashboard_df,
    [
        "Sector",
        "Industry",
        "Business_Sector"
    ]
)


profile_col = find_column(
    dashboard_df,
    [
        "Risk_Profile",
        "Risk_Profile_Type",
        "Borrower_Risk_Profile"
    ]
)


# ============================================================
# SIDEBAR FILTERS
# ============================================================

st.sidebar.markdown(
    "### Filters"
)


# Sector

if sector_col:

    sectors = sorted(
        dashboard_df[
            sector_col
        ]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    selected_sector = st.sidebar.selectbox(
        "Sector",
        ["All"] + sectors
    )

else:

    selected_sector = "All"


# Risk Band

selected_band = st.sidebar.selectbox(
    "EWS Risk Band",
    [
        "All",
        "Green",
        "Yellow",
        "Amber",
        "Red",
        "Critical"
    ]
)


# Borrower Risk Profile

if profile_col:

    profiles = sorted(
        dashboard_df[
            profile_col
        ]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    selected_profile = st.sidebar.selectbox(
        "Borrower Risk Profile",
        ["All"] + profiles
    )

else:

    selected_profile = "All"


# ============================================================
# APPLY FILTERS
# ============================================================

filtered_df = dashboard_df.copy()


if (
    sector_col
    and selected_sector != "All"
):

    filtered_df = filtered_df[
        filtered_df[
            sector_col
        ] == selected_sector
    ]


if (
    risk_band_col
    and selected_band != "All"
):

    filtered_df = filtered_df[
        filtered_df[
            risk_band_col
        ] == selected_band
    ]


if (
    profile_col
    and selected_profile != "All"
):

    filtered_df = filtered_df[
        filtered_df[
            profile_col
        ] == selected_profile
    ]


# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3, tab4, tab5 = st.tabs(
    [
        "📊 Risk Overview",
        "🔎 Evidence Pack",
        "📈 Trend & Peer Analytics",
        "✍️ Human Review",
        "📜 Governance & Audit Trail"
    ]
)


# ============================================================
# TAB 1 — RISK OVERVIEW
# ============================================================

with tab1:

    st.subheader(
        "Portfolio Risk Overview"
    )


    # --------------------------------------------------------
    # KPI CALCULATIONS
    # --------------------------------------------------------

    total_borrowers = len(
        filtered_df
    )


    if risk_band_col:

        critical_count = len(
            filtered_df[
                filtered_df[
                    risk_band_col
                ] == "Critical"
            ]
        )

        red_critical_count = len(
            filtered_df[
                filtered_df[
                    risk_band_col
                ].isin(
                    [
                        "Red",
                        "Critical"
                    ]
                )
            ]
        )

    else:

        critical_count = 0
        red_critical_count = 0


    # Alert count

    if (
        not alerts_df.empty
        and borrower_id_col
        and borrower_id_col
        in alerts_df.columns
    ):

        active_alerts = len(
            alerts_df[
                alerts_df[
                    borrower_id_col
                ].astype(str).isin(
                    filtered_df[
                        borrower_id_col
                    ].astype(str)
                )
            ]
        )

    else:

        active_alerts = len(
            alerts_df
        )


    # Average score

    if score_col:

        score_series = pd.to_numeric(
            filtered_df[
                score_col
            ],
            errors="coerce"
        )

        average_score = (
            score_series.mean()
            if not score_series.empty
            else 0
        )

    else:

        average_score = 0


    # --------------------------------------------------------
    # KPI CARDS
    # --------------------------------------------------------

    col1, col2, col3, col4, col5 = st.columns(5)


    with col1:

        st.metric(
            "Total Borrowers",
            total_borrowers
        )


    with col2:

        st.metric(
            "Critical",
            critical_count
        )


    with col3:

        st.metric(
            "Red + Critical",
            red_critical_count
        )


    with col4:

        st.metric(
            "Active Alerts",
            active_alerts
        )


    with col5:

        st.metric(
            "Average EWS Score",
            f"{average_score:.1f}"
        )


    st.divider()


    # --------------------------------------------------------
    # RISK DISTRIBUTION
    # --------------------------------------------------------

    col_left, col_right = st.columns(2)


    with col_left:

        st.subheader(
            "EWS Risk Band Distribution"
        )

        if risk_band_col:

            risk_distribution = (
                filtered_df[
                    risk_band_col
                ]
                .value_counts()
                .reindex(
                    [
                        "Green",
                        "Yellow",
                        "Amber",
                        "Red",
                        "Critical"
                    ],
                    fill_value=0
                )
            )

            st.bar_chart(
                risk_distribution
            )


    with col_right:

        st.subheader(
            "Borrower Risk Profile"
        )

        if profile_col:

            profile_distribution = (
                filtered_df[
                    profile_col
                ]
                .value_counts()
            )

            st.bar_chart(
                profile_distribution
            )


    st.divider()


    # --------------------------------------------------------
    # ACCOUNT LEVEL DATA
    # --------------------------------------------------------

    st.subheader(
        "Account-Level EWS Scores"
    )


    preferred_columns = [
        "Borrower_ID",
        "Borrower_Name",
        "Account_Number",
        "Sector",
        "City",
        "Risk_Profile",
        "External_Rating",
        "Annual_Turnover_Cr",
        "Total_Debt_Cr",
        "TNW_Cr",
        "Overall_Normalized_Score",
        "Overall_Risk_Score",
        "Risk_Band",
        "Final_Status"
    ]


    available_columns = [
        col
        for col in preferred_columns
        if col in filtered_df.columns
    ]


    if available_columns:

        st.dataframe(
            filtered_df[
                available_columns
            ],
            use_container_width=True,
            height=450
        )

    else:

        st.dataframe(
            filtered_df,
            use_container_width=True,
            height=450
        )


    # --------------------------------------------------------
    # DOWNLOAD
    # --------------------------------------------------------

    st.download_button(
        label="📥 Download Portfolio View",
        data=filtered_df.to_csv(
            index=False
        ).encode("utf-8"),
        file_name="EWS_Portfolio_View.csv",
        mime="text/csv"
    )


# ============================================================
# TAB 2 — EVIDENCE PACK
# ============================================================

with tab2:

    st.subheader(
        "🔎 Explainability & Evidence Pack"
    )


    if borrower_id_col:

        borrower_list = (
            filtered_df[
                borrower_id_col
            ]
            .dropna()
            .astype(str)
            .tolist()
        )


        if borrower_list:

            selected_borrower = st.selectbox(
                "Select Borrower / Account",
                borrower_list,
                key="evidence_borrower"
            )


            selected_data = filtered_df[
                filtered_df[
                    borrower_id_col
                ].astype(str)
                == str(selected_borrower)
            ]


            if not selected_data.empty:

                acc_info = (
                    selected_data.iloc[0]
                )


                # ------------------------------------------------
                # BORROWER INFORMATION
                # ------------------------------------------------

                st.markdown(
                    "### Borrower Information"
                )


                info1, info2, info3, info4 = st.columns(4)


                name_col = find_column(
                    dashboard_df,
                    [
                        "Borrower_Name",
                        "Company_Name"
                    ]
                )


                with info1:

                    st.metric(
                        "Borrower",
                        acc_info.get(
                            name_col,
                            "N/A"
                        )
                        if name_col
                        else "N/A"
                    )


                with info2:

                    st.metric(
                        "Sector",
                        acc_info.get(
                            sector_col,
                            "N/A"
                        )
                        if sector_col
                        else "N/A"
                    )


                with info3:

                    st.metric(
                        "Rating",
                        acc_info.get(
                            "External_Rating",
                            "N/A"
                        )
                    )


                with info4:

                    st.metric(
                        "Risk Band",
                        acc_info.get(
                            risk_band_col,
                            "N/A"
                        )
                        if risk_band_col
                        else "N/A"
                    )


                st.divider()


                # ------------------------------------------------
                # EWS ASSESSMENT
                # ------------------------------------------------

                st.markdown(
                    "### EWS Assessment"
                )


                c1, c2, c3, c4 = st.columns(4)


                with c1:

                    score_value = (
                        acc_info.get(
                            score_col,
                            "N/A"
                        )
                        if score_col
                        else "N/A"
                    )

                    try:

                        score_display = (
                            f"{float(score_value):.2f}"
                        )

                    except Exception:

                        score_display = str(
                            score_value
                        )


                    st.metric(
                        "Overall EWS Score",
                        score_display
                    )


                with c2:

                    st.metric(
                        "Risk Band",
                        acc_info.get(
                            risk_band_col,
                            "N/A"
                        )
                        if risk_band_col
                        else "N/A"
                    )


                with c3:

                    st.metric(
                        "Final Status",
                        acc_info.get(
                            status_col,
                            "N/A"
                        )
                        if status_col
                        else "N/A"
                    )


                with c4:

                    st.metric(
                        "Critical Override",
                        acc_info.get(
                            critical_col,
                            "N/A"
                        )
                        if critical_col
                        else "N/A"
                    )


                # ------------------------------------------------
                # ALERTS
                # ------------------------------------------------

                st.markdown(
                    "### 🚨 Active EWS Alerts"
                )


                if (
                    not alerts_df.empty
                    and borrower_id_col
                    in alerts_df.columns
                ):

                    borrower_alerts = alerts_df[
                        alerts_df[
                            borrower_id_col
                        ].astype(str)
                        == str(selected_borrower)
                    ].copy()


                    if not borrower_alerts.empty:

                        sort_columns = [
                            col
                            for col in [
                                "Score",
                                "Normalized_Score"
                            ]
                            if col in borrower_alerts.columns
                        ]


                        if sort_columns:

                            borrower_alerts = (
                                borrower_alerts
                                .sort_values(
                                    by=sort_columns[0],
                                    ascending=False
                                )
                            )


                        st.dataframe(
                            borrower_alerts,
                            use_container_width=True
                        )

                    else:

                        st.success(
                            "No active EWS alerts."
                        )


                # ------------------------------------------------
                # RAW EWS DATA
                # ------------------------------------------------

                st.markdown(
                    "### 📋 EWS Input Data"
                )


                if (
                    not ews_raw_df.empty
                    and borrower_id_col
                    in ews_raw_df.columns
                ):

                    raw_data = ews_raw_df[
                        ews_raw_df[
                            borrower_id_col
                        ].astype(str)
                        == str(selected_borrower)
                    ]


                    if not raw_data.empty:

                        st.dataframe(
                            raw_data,
                            use_container_width=True
                        )

                    else:

                        st.info(
                            "No raw EWS data available "
                            "for this borrower."
                        )


                # ------------------------------------------------
                # INDICATOR SCORE BREAKDOWN
                # ------------------------------------------------

                st.markdown(
                    "### 📊 Indicator Score Breakdown"
                )


                score_columns = [
                    col
                    for col in ews_df.columns
                    if (
                        "score" in col.lower()
                        or "normalized" in col.lower()
                        or "band" in col.lower()
                    )
                ]


                if score_columns:

                    score_breakdown = selected_data[
                        [
                            col
                            for col in score_columns
                            if col
                            in selected_data.columns
                        ]
                    ]


                    st.dataframe(
                        score_breakdown.T,
                        use_container_width=True
                    )


# ============================================================
# TAB 3 — TREND & PEER ANALYTICS
# ============================================================

with tab3:

    st.subheader(
        "📈 Trend & Peer Analytics"
    )


    trend_data = load_db_table(
        "trend_analytics_results"
    )


    peer_data = load_db_table(
        "peer_benchmark_results"
    )


    col_a, col_b = st.columns(2)


    with col_a:

        st.markdown(
            "### 📉 Quarterly Metric Deterioration"
        )


        if not trend_data.empty:

            st.dataframe(
                trend_data,
                use_container_width=True
            )

        else:

            st.info(
                "No trend analytics generated yet."
            )


    with col_b:

        st.markdown(
            "### 🏢 Peer Group Benchmarking"
        )


        if not peer_data.empty:

            st.dataframe(
                peer_data,
                use_container_width=True
            )

        else:

            st.info(
                "No peer benchmark results generated yet."
            )


    # --------------------------------------------------------
    # CREDIT MONITORING
    # --------------------------------------------------------

    st.divider()


    st.subheader(
        "📋 Credit Monitoring Results"
    )


    if not cm_df.empty:

        st.dataframe(
            cm_df,
            use_container_width=True,
            height=400
        )

    else:

        st.info(
            "No Credit Monitoring results available."
        )


# ============================================================
# TAB 4 — HUMAN REVIEW
# ============================================================

with tab4:

    st.subheader(
        "✍️ Human Credit Review & Decisioning"
    )


    st.info(
        "The system provides risk signals and supporting "
        "evidence. Final credit decisions remain with the "
        "authorized Credit Officer."
    )


    if borrower_id_col:

        borrower_list = (
            filtered_df[
                borrower_id_col
            ]
            .dropna()
            .astype(str)
            .tolist()
        )


        if borrower_list:

            acc_to_review = st.selectbox(
                "Select Borrower / Account",
                borrower_list,
                key="review_acc"
            )


            # ------------------------------------------------
            # CURRENT RISK
            # ------------------------------------------------

            review_row = filtered_df[
                filtered_df[
                    borrower_id_col
                ].astype(str)
                == str(acc_to_review)
            ]


            if not review_row.empty:

                review_row = (
                    review_row.iloc[0]
                )


                r1, r2, r3 = st.columns(3)


                with r1:

                    st.metric(
                        "Current EWS Score",
                        review_row.get(
                            score_col,
                            "N/A"
                        )
                        if score_col
                        else "N/A"
                    )


                with r2:

                    st.metric(
                        "Current Risk Band",
                        review_row.get(
                            risk_band_col,
                            "N/A"
                        )
                        if risk_band_col
                        else "N/A"
                    )


                with r3:

                    st.metric(
                        "Final Status",
                        review_row.get(
                            status_col,
                            "N/A"
                        )
                        if status_col
                        else "N/A"
                    )


            st.markdown(
                "### Credit Officer Action"
            )


            decision = st.radio(
                "Decision",
                [
                    "Accept Alert (Escalate to Remediation)",
                    "Override Risk Band",
                    "Close as False Positive"
                ]
            )


            rationale = st.text_area(
                "Mitigation Rationale / Comments",
                "",
                height=120
            )


            reviewer_id = st.text_input(
                "Reviewer ID",
                "CO_001"
            )


            if st.button(
                "Submit Decision",
                type="primary"
            ):

                if not rationale.strip():

                    st.error(
                        "Please provide a rationale "
                        "before submitting."
                    )

                else:

                    save_audit_action(
                        account_num=acc_to_review,
                        decision=decision,
                        rationale=rationale,
                        reviewer_id=reviewer_id
                    )


                    st.success(
                        f"Decision for {acc_to_review} "
                        f"logged successfully."
                    )


# ============================================================
# TAB 5 — GOVERNANCE & AUDIT TRAIL
# ============================================================

with tab5:

    st.subheader(
        "📜 Governance & Audit Trail"
    )


    # --------------------------------------------------------
    # AUDIT HISTORY
    # --------------------------------------------------------

    st.markdown(
        "### Audit History"
    )


    audit_df = load_db_table(
        "audit_trail"
    )


    if not audit_df.empty:

        st.dataframe(
            audit_df,
            use_container_width=True,
            height=400
        )


        st.download_button(
            label="📥 Download Audit History",
            data=audit_df.to_csv(
                index=False
            ).encode("utf-8"),
            file_name="EWS_Audit_Trail.csv",
            mime="text/csv"
        )


    else:

        st.info(
            "No audit logs recorded yet."
        )


    st.divider()


    # --------------------------------------------------------
    # DATASET INFORMATION
    # --------------------------------------------------------

    st.markdown(
        "### Dataset Information"
    )


    info1, info2, info3, info4 = st.columns(4)


    with info1:

        st.metric(
            "Synthetic Borrowers",
            len(borrower_df)
            if not borrower_df.empty
            else 0
        )


    with info2:

        st.metric(
            "EWS Records",
            len(ews_df)
        )


    with info3:

        st.metric(
            "Credit Monitoring Records",
            len(cm_df)
        )


    with info4:

        st.metric(
            "EWS Alerts",
            len(alerts_df)
            if not alerts_df.empty
            else 0
        )


    # --------------------------------------------------------
    # FILE STATUS
    # --------------------------------------------------------

    st.markdown(
        "### Data File Status"
    )


    file_status = pd.DataFrame(
        {
            "File": [
                "Borrower Master",
                "EWS Raw Inputs",
                "EWS Results",
                "Credit Monitoring Raw",
                "Credit Monitoring Results",
                "EWS Alerts"
            ],

            "Status": [
                "Available"
                if BORROWER_FILE.exists()
                else "Missing",

                "Available"
                if EWS_RAW_FILE.exists()
                else "Missing",

                "Available"
                if EWS_FILE.exists()
                else "Missing",

                "Available"
                if CM_RAW_FILE.exists()
                else "Missing",

                "Available"
                if CM_FILE.exists()
                else "Missing",

                "Available"
                if ALERT_FILE.exists()
                else "Missing"
            ]
        }
    )


    st.dataframe(
        file_status,
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "AI EWS & Credit Monitoring System | "
    "Synthetic Corporate Borrower Dataset | "
    "Human-in-the-Loop Credit Decisioning"
)